SH-11 Main Menü View
dmorbitzer/smart-home-mobile-app pull request #4
Opened 2023-04-10 17:37 UTC by Swaggener

2023-04-10 18:24 UTC, dmorbitzer requested changes

2023-04-10 18:24 UTC, dmorbitzer commented on App.js
> +  uri: "http://192.168.0.68:8080/api/graphql",
Hier bitte die url aus zeile 6 nutzen.

2023-04-10 18:24 UTC, dmorbitzer commented on components/SHButton.js
> +export default function SHButton(props) {
Mir ist nicht ganz klar für was SH steht, vielleicht ausschreiben?

2023-04-10 18:24 UTC, dmorbitzer commented on components/SHButton.js
> +        }}
Das "active" Attribute wird hier nicht übergeben?

2023-04-10 18:24 UTC, dmorbitzer commented on landing-page/LandingPage.js
> +  }
Das abrufen der Daten bitte in ein eigenes File um einfacher Testen zu können. Tests fehlen für diese Component komplett.

2023-04-10 18:24 UTC, dmorbitzer commented on landing-page/LandingPage.js
> +    servicesList.push(
Das rendern der Icons würde ich eher in der SHButton Component sehen, bzw vielleicht sogar in einer eigenen Component? Um den code aufgeräumter zu haben. Vielleicht haben wir auch eine Möglichkeit das laden der icons generischer zu geestalten? Was passiert wenn der Service nicht "Katzenprofil", "Katzenfütterung" oder "Katzenerkennung" heißt?

2023-04-10 18:24 UTC, dmorbitzer commented on landing-page/LandingPage.js
> +  for (let i = 0; i < data.services.edges.length; i++) {
Hier werden alle Services angezeigt, egal ob sie active oder nicht sind oder?

2023-04-10 18:24 UTC, dmorbitzer commented on landing-page/LandingPage.js
> +export default function LandingPage({ navigation }) {
Finde den Namen eher missverständlich, wäre MainMenu nicht besser?

2023-04-11 18:56 UTC, Swaggener commented on components/SHButton.js
> +        }}
Nein, da der Button gar nicht angezeigt wird, muss "active" auch nicht übergeben werden

2023-04-17 08:01 UTC, merged